### ISSUE TITLE
Comments about password

### ISSUE THREAD

**Issue by KarenStackoski** [KarenStackoski/CalculosMatematicos#1]
@KoroTT acho legal deixar comentários no código do arquivo src/Utilities/PasswordUtilities.java para que todos possam entender melhor como funciona o processo de gerar uma senha.

**Comment by KoroTT** [comment]
Opa, pode deixar que assim que possível vou comentar
Quero aproveitar pra revisar o mesmo e garantir que ele vai estar com a
nossa cara


Karen Stackoski ***@***.***> escreveu (quinta, 11/04/2024
à(s) 09:16):
